### ISSUE TITLE
UPDATE THE BUTTONS AND SECTIONS SO THEY CAN WORK AGAIN

### ISSUE THREAD

**Issue by itsreimau** [Mengkodingan/ckptw#12]
Since there is now a new way to create buttons and sections, please update ckptw now to be able to do this.

**Comment by JastinXyz** [comment]
Already planned, maybe it will be implemented in the next update 👍

**Comment by Cyberkingcr7** [comment]
> Already planned, maybe it will be implemented in the next update 👍

really? yall found the work around for buttons?

**Comment by JastinXyz** [comment]
@Cyberkingcr7 Just use InteractiveMessage (or whatever it's called), it seems like buttons can be used... But some issues like messages that have buttons I think are not supported on Whatsapp Desktop and web(?)

**Comment by Cyberkingcr7** [comment]
> @Cyberkingcr7 Just use InteractiveMessage (or whatever it's called), it seems like buttons can be used... But some issues like messages that have buttons I think are not supported on Whatsapp Desktop and web(?)

well i dont see any references in this library of what you talkinag about?

**Comment by JastinXyz** [comment]
@Cyberkingcr7 There is no reference to that in this repo. It is still under development. But if you look for references in other repos that develop bots using Baileys, you might find what you're looking for.

**Comment by JastinXyz** [comment]
Buttons and sections can now be used in the latest version 👍

**Comment by Cyberkingcr7** [comment]
Thanks this is a great repo if you get time please just work a bit on poll message, getting the keys and etc

**Comment by JastinXyz** [comment]
@Cyberkingcr7 Do you mean [this poll message](https://github.com/Mengkodingan/ckptw?tab=readme-ov-file#poll-message) or what?
