### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by CauaCodeDev** [Mengkodingan/ckptw#15]
Is it possible to send a button without needing to receive a message first?

**Comment by JastinXyz** [comment]
@CauaCodeDev what do you mean? can you give me an example?

**Comment by JastinXyz** [comment]
@CauaCodeDev what do you mean? are there any examples you can give?

**Comment by CauaCodeDev** [comment]
> @CauaCodeDevO que você quer dizer? Tem algum exemplo que você possa dar?


import { Client, Events, MessageType, ButtonBuilder } from "@mengkodingan/ckptw";

let button = new ButtonBuilder()
    .setId('!ping')
    .setDisplayText('command Ping')
    .setType('quick_reply')
    .build();

let button2 = new ButtonBuilder()
    .setId('id2')
    .setDisplayText('copy code')
    .setType('cta_copy')
    .setCopyCode('hello world')
    .build();

let button3 = new ButtonBuilder()
    .setId('id3')
    .setDisplayText('@mengkodingan/ckptw')
    .setType('cta_url')
    .setURL('https://github.com/mengkodingan/ckptw')
    .setMerchantURL('https://github.com/mengkodingan')
    .build();

const bot = new Client({
    prefix: "!",
    printQRInTerminal: true,
    readIncommingMsg: true
});

bot.ev.once(Events.ClientReady, (m) => {
    console.log(`ready at ${m.user.id}`);
    
    bot.core.sendInteractiveMessage(m.user.id, { 
        body: 'this is body', 
        footer: 'this is footer', 
        nativeFlowMessage: { buttons: [button, button2, button3] }
    })
});

bot.launch();

**Comment by JastinXyz** [comment]
Ohh I see. It should be possible to manually initiate the Ctx class and then use the functions in the Ctx class, but this doesn't seem like best practice.

Maybe I will consider adding such a feature to solve cases like this in the future.

**Comment by CauaCodeDev** [comment]
> Ah, entendi. Deveria ser possível iniciar manualmente a classe Ctx e então usar as funções na classe Ctx, mas isso não parece ser a melhor prática.
> 
> Talvez eu considere adicionar esse recurso para resolver casos como esse no futuro.

Could you give an example, please?
