### ISSUE TITLE
[SUGGESTION] Add new updates

### ISSUE THREAD

**Issue by itsreimau** [Mengkodingan/ckptw#16]
## Suggestion (Hopefully added)
Can you add a new option to the Client that automatically gets Mentions on texts to be sent. So don't use ```ctx.getMentioned()``` on every message to be sent.

```javascript
import { Client } from "@mengkodingan/ckptw";

const bot = new Client({
    prefix: "!",
    printQRInTerminal: true,
    readIncommingMsg: true,
    autoMentionedMsg: true // This is just an example, whatever you want to call it.
});

ctx.reply({ text: "Hello World!", mentions: ctx.getMentioned() }); // It would take a long time to add them one by one.

ctx.reply({ text: "Hello World!" }); // Like this, automatically using ctx.getMentioned()
```

---

Added a function to easily get the media buffer without having to download it using other functions.
```javascript
// So the buffer media can be retrieved via ctx, or m.

// For ctx
ctx.msg.media.toBuffer();  // Media to buffer
ctx._msg.media.toBuffer(); // Media to buffer
ctx.quoted.media.toBuffer();  // Media to buffer

// For m
m.media.toBuffer(); // Media to Buffer
```

---

If you want to add it I would be very happy!

**Comment by JastinXyz** [comment]
Thank you for your feedback! You can use the latest version of ckptw which already has these features available. Details of what features have been added are at https://github.com/Mengkodingan/ckptw/releases/tag/v4.3.6 👍 

Feel free to close this issue if there is nothing more to discuss.

**Comment by itsreimau** [comment]
Thank you so much, you are so cool! I am very happy now.
