### ISSUE TITLE
[ERROR] Connection closed, update baileys to v6.7.7

### ISSUE THREAD

**Issue by itsreimau** [Mengkodingan/ckptw#17]
It seems like the `@whiskeysockets/baileys` version is still using the old version. My suggestion, instead of using the latest update like `^6.7.7`, it is better to use `github:WhiskeySockets/Baileys`.

**Comment by Cyberkingcr7** [comment]
@JastinXyz in addition to this issue here are the logs and this started yesterday , hopefully you will respond soon:
 ```0|my-app | connection closed due to Error: Connection Failure 0|my-app | at WebSocketClient.<anonymous> (C:\Users\suijin\Desktop\neko\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:529:13) 0|my-app | at WebSocketClient.emit (node:events:518:28) 0|my-app | at C:\Users\suijin\Desktop\neko\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:241:35 0|my-app | at Object.decodeFrame (C:\Users\suijin\Desktop\neko\node_modules\@whiskeysockets\baileys\lib\Utils\noise-handler.js:149:17) 0|my-app | at WebSocketClient.onMessageReceived (C:\Users\suijin\Desktop\neko\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:217:15) 0|my-app | at WebSocketClient.emit (node:events:518:28) 0|my-app | at WebSocket.<anonymous> (C:\Users\suijin\Desktop\neko\node_modules\@whiskeysockets\baileys\lib\Socket\Client\web-socket-client.js:46:100) 0|my-app | at WebSocket.emit (node:events:518:28) 0|my-app | at Receiver.receiverOnMessage (C:\Users\suijin\Desktop\neko\node_modules\ws\lib\websocket.js:1211:20) 0|my-app | at Receiver.emit (node:events:518:28) { 0|my-app | data: { reason: '405', location: 'rva' }, 0|my-app | isBoom: true, 0|my-app | isServer: false, 0|my-app | output: { 0|my-app | statusCode: 405, 0|my-app | payload: { 0|my-app | statusCode: 405, 0|my-app | error: 'Method Not Allowed', 0|my-app | message: 'Connection Failure' 0|my-app | }, 0|my-app | headers: {} 0|my-app | } 0|my-app | } , reconnecting true\```

**Comment by JastinXyz** [comment]
Baileys was updated to v6.7.7 in ckptw latest version :+1:

**Comment by this-is-space** [comment]
data: { reason: '405', location: 'atn' },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: {
      statusCode: 405,
      error: 'Method Not Allowed',
      message: 'Connection Failure'
    },
    headers: {}
  }
} , reconnecting  true

Issue remains same

**Comment by JastinXyz** [comment]
@this-is-space Try specifying a custom whatsapp version in the client constructor.

```js
const bot = new Client({
    prefix: "!",
    readIncommingMsg: true,
    WAVersion: [2, 3000, 1015901307] // add this
});
```

using version `2, 3000, 1015901307` is worked for me.

**Comment by Cyberkingcr7** [comment]
@JastinXyz doesnt work for me
