### ISSUE TITLE
Bot Can't Mention any user

### ISSUE THREAD

**Issue by this-is-space** [Mengkodingan/ckptw#19]
I want to mention users in my message but there are no clear documentation 
and also how to join group using group link using the bot

**Comment by JastinXyz** [comment]
To mention users, you can add "mentions" property by filling its value with an array of **jid** that will be mentioned when sending a message.

```js
ctx.reply({ text: 'testing', mentions: ['628123456789@s.whatsapp.net'] })
```

To join group using invite link:

```js
// the invite link is: https://chat.whatsapp.com/DlLSc6aOoWwDss3tHS0V4y
ctx.groups.acceptInvite('DlLSc6aOoWwDss3tHS0V4y'); // only using the invite code
```

**Comment by this-is-space** [comment]
ctx.reply({ text: 'testing', mentions: ['628123456789@s.whatsapp.net'] })

I want to mention in this Way 

ctx.reply("Hello ${'628123456789@s.whatsapp.net'}")

// Example in chat 
Hello @JastinXyz

**Comment by JastinXyz** [comment]
🤨
