### ISSUE TITLE
sending sticker

### ISSUE THREAD

**Issue by thoriqazzikraa** [Mengkodingan/ckptw#21]
i can't sending sticker using image from file path

```js
const media = await ctx.getMediaMessage(ctx.msg, "buffer")
fs.writeFileSync(__dirname, media)
await ctx.reply({ sticker:  { url: __dirname }})
```

the sticker is blank, but working with send image

![Screenshot_2024-08-28-02-01-07-79_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/user-attachments/assets/e24d5ffa-9550-499e-9368-676511bf2620)

**Comment by thoriqazzikraa** [comment]
.

**Comment by itsreimau** [comment]
> i can't sending sticker using image from file path
> 
> ```js
> const media = await ctx.getMediaMessage(ctx.msg, "buffer")
> fs.writeFileSync(__dirname, media)
> await ctx.reply({ sticker:  { url: __dirname }})
> ```
> 
> the sticker is blank, but working with send image
> 
> ![Screenshot_2024-08-28-02-01-07-79_6012fa4d4ddec268fc5c7112cbb265e7](https://private-user-images.githubusercontent.com/89589243/361939830-e24d5ffa-9550-499e-9368-676511bf2620.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTcxMjQsIm5iZiI6MTcyNTQxNjgyNCwicGF0aCI6Ii84OTU4OTI0My8zNjE5Mzk4MzAtZTI0ZDVmZmEtOTU1MC00OTllLTkzNjgtNjc2NTExYmYyNjIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAyMjcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MGQ1ZmNkMDU2MGY1MGE2OWU3NWQ1ZWU0N2UzNjYyMzg1NjY1Yjk4MGQ5Nzg4YThhNTM5ZGE0MmE4NjQxNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1CEbmw49hoxGbhZLCpgX5dG_2KCmuGMWE6DKGgRq8tE)

You can use wa-sticker-formatter to send stickers.
