### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Cyberkingcr7** [Mengkodingan/ckptw#23]
Good evening i wanted to know if you could refer me to WhatsApp channels documentation or explain to me if bot works there and etc.

**Comment by JastinXyz** [comment]
@Cyberkingcr7 Actually, the documentation is already planned, and is under development. But because I am the one who maintains this library and I also have other activities, it takes a little longer to complete the documentation (whether it will become a stalled project or not).

**Comment by Cyberkingcr7** [comment]
Yes i understand and i respect that bro this is the best library in my opinion nevertheless could you just show me how i can quote instead of mentioning, thats my only setback right now. Thanks!!

**Comment by Cyberkingcr7** [comment]
Finally fixed it, thanks.
