### ISSUE TITLE
carousel message

### ISSUE THREAD

**Issue by Cyberkingcr7** [Mengkodingan/ckptw#25]
Hi, im not sure if its me only but when i click the buttons on carousel i get kicked out of whatsapp basically like a bug. Please look into it and update me . Thanks

**Comment by ZTRdiamond** [comment]
> Hi, im not sure if its me only but when i click the buttons on carousel i get kicked out of whatsapp basically like a bug. Please look into it and update me . Thanks

That is whatsapp issue, the carousel message is an experimental feature of whatsapp so there's a lot of bugs.

**Comment by Cyberkingcr7** [comment]
Alright thanks ... If only I could use it without the button

**Comment by ZTRdiamond** [comment]
> Alright thanks ... If only I could use it without the button

maybe it is possible, I don't know because I don't use it
