### ISSUE TITLE
Error: Pairing Code Spam

### ISSUE THREAD

**Issue by itsreimau** [Mengkodingan/ckptw#8]
So I used the pairing code for connection but the pairing code actually created spam. So I can't see the pairing code because it's drowning in spam and the pairing code doesn't work.

[Code here](https://github.com/itsreimau/ckptw-wabot/blob/d41196c1d0366856130fb19ca78ae7e0ce0281eb/main.js#L29)

**Comment by itsreimau** [comment]
dongo gw, state nya belum di hapus :v

**Comment by JastinXyz** [comment]
aduhai

**Comment by ZTRdiamond** [comment]
> dongo gw, state nya belum di hapus :v

smart😹
